### ISSUE TITLE
401 on some calls

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/syncstorage-loadtest#2] opened 2017-04-27 07:33 UTC
It looks like the service produces random 401s. Running the test several times, I get 401 on random places.

@rfk I think that's what happened for me with the original test. Are you able to reproduce the issue on your side ?  see README for running the test 5 times

**Comment by tarekziade** [comment] 2017-04-27 08:25
Ok so this is a signature problem. It happens only on GETs that have a query string or PUTs

```
GET /1.5/1515071/storage/clients?newer=1493095888&full=1
PUT /1.5/1606941/storage/meta/global
```

I suspect that might be related to the normalization code at https://github.com/mozilla-services/syncstorage-loadtest/blob/master/storage/__init__.py#L132

digging...

**Comment by tarekziade** [comment] 2017-04-28 07:12
@rfk what do you think?

**Comment by rfk** [comment] 2017-05-01 03:34
I haven't got to the bottom of this yet, but I'm trying to debug by pointing it at a local running instance of syncserver, and printing out the auth headers from the server's point of view.  For requests with query parameters, the incoming URL seen by the server is reportedly:

  `u'hawk.1.header\n1493608988\nIMzH/nc=\nGET\n/storage/1.5/39/storage/clients?newer=1493574734&full=1&newer=1493574734&full=1\nlocalhost\n5000\n\n\n'`

Which has all of the query params duplicated.  So I wonder if it's signing a `path_qs` with the correct query params, but then somehow appending them again when it makes the actual requests to the server..?

**Comment by tarekziade** [comment] 2017-11-14 08:27
Looks like I still get some 401 from time to time. But it works mostr of the time. Not sure what's happening yet

**Comment by tarekziade** [comment] 2017-11-15 13:28
I am kind of confused why the 1st GET call fails randomly with a 401 for me. It works 4 times out of 5 here. Maybe it's a timing issue with the assertion but I did not find any pattern yet

@rfk any idea what could be going wrong?  thanks

**Comment by rfk** [comment] 2017-11-27 02:20
I can confirm I see sporadic failures that look like this, with an error message of "connection closed":

```
)$ bin/molotov --max-runs 100 -cxv loadtest.py
**** Molotov v1.5. Happy breaking! ****
Preparing 1 worker...
OK
ClientConnectionError('Connection closed',)
  File "/home/rfk/repos/mozilla/services/syncstorage-loadtest/local/lib/python3.5/site-packages/molotov/work
er.py", line 173, in step
    **scenario['kw'])
  File "loadtest.py", line 112, in test
    await resp.json()
  File "/home/rfk/repos/mozilla/services/syncstorage-loadtest/local/lib/python3.5/site-packages/aiohttp/clie
nt_reqrep.py", line 785, in json
    yield from self.read()
  File "/home/rfk/repos/mozilla/services/syncstorage-loadtest/local/lib/python3.5/site-packages/aiohttp/clie
nt_reqrep.py", line 746, in read
    self._content = yield from self.content.read()
  File "/home/rfk/repos/mozilla/services/syncstorage-loadtest/local/lib/python3.5/site-packages/aiohttp/stre
ams.py", line 607, in read
    return (yield from super().read(n))
  File "/home/rfk/repos/mozilla/services/syncstorage-loadtest/local/lib/python3.5/site-packages/aiohttp/stre
ams.py", line 299, in read
    raise self._exception
SUCCESSES: 19 | FAILURES: 1
*** Bye ***
```

But if I try to add `-vv` to get more details of the requests, then is seems I'm unable to reproduce.  Doing ` bin/molotov --max-runs 100 -cxvv loadtest.py` runs to completion with 100 successes every time I've tried it.

@tarekziade does this match what you're observing, or is it a different error?

**Comment by rfk** [comment] 2019-02-27 21:32
@rbillings is this causing you issues still, or can we close it out?

**Comment by rbillings** [comment] 2019-02-28 14:42
I remember I had some issues last November that were resolved by reducing the token_duration.  I believe this can be closed out.

**Closed** 2019-02-28 18:55 UTC
